# Generated by Django 6.0.2 on 2026-02-16 03:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('is_active_employee', models.BooleanField(default=True, verbose_name='Активдүү')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Толук аты-жөнү')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('passport_number', models.CharField(max_length=50, verbose_name='Паспорт номери')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.employee', verbose_name='Түзгөн кызматкер')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Жалгыз сумма')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Процент (%)')),
                ('months', models.IntegerField(default=10, verbose_name='Айлар саны')),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Айлык төлөм')),
                ('total_with_interest', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Процент менен жалпы')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Калган сумма')),
                ('status', models.CharField(choices=[('active', 'Активдүү'), ('completed', 'Жабылган'), ('overdue', 'Мөөнөтү өткөн')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Башталган күнү')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.customer', verbose_name='Кардар')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.employee', verbose_name='Берген кызматкер')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_number', models.IntegerField(verbose_name='Ай номери')),
                ('due_date', models.DateField(verbose_name='Төлөө күнү')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Төлөнгөн')),
                ('paid_date', models.DateTimeField(blank=True, null=True, verbose_name='Төлөнгөн күнү')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Төлөнгөн сумма')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='loans.loan', verbose_name='Кредит')),
            ],
            options={
                'ordering': ['month_number'],
            },
        ),
    ]
